services:
  app:
    image: partnership-workshop-docker.jfrog.io/ecs-docker-compose-workshop-app:${run_number}
    restart: always
    ports:
      - 443:443
    networks:
      - appnet
networks:
  appnet:
